version: '3.7'

services:
  identity-server:
    image: oleksandrbondarenko777/identity-server:latest
    container_name: identity-server
    ports:
      - '8080:5000'
    depends_on:
      - sql-server-db

  core-api:
    image: oleksandrbondarenko777/core-api:latest
    container_name: core-api
    ports:
      - '8081:5002'
    depends_on:
      - sql-server-db

  ui:
    image: oleksandrbondarenko777/online-shop-ui:latest
    container_name: online-shop-ui
    ports:
      - '8082:3000'

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql-server-17
    ports:
      - '2433:1433'
    environment:
      SA_PASSWORD: "Pass1234Qq"
      ACCEPT_EULA: "Y"